### ISSUE TITLE
key press or simulating keyboard

### ISSUE THREAD

**Issue by srichand2095** [gilzoide/godot-lua-pluginscript#21]
hey how can i get input from keyboard and mouse.

**Comment by gilzoide** [comment]
Hi!
In terms of Godot functionality, you do stuff in Lua scripts the same way that you would in GDScript or C#, you just have to use the right objects/methods.
The different stuff is just the language. For example, in Lua, to call methods in the script instance, you have to use `self:<your method name>(...)` instead of just `<your method name>(...)`. To access properties, you need to use `self.<your property name>` instead of just `<your property name>`.

Check out Godot's documentation for more information on how to handle inputs (including keyboard and mouse): https://docs.godotengine.org/en/stable/tutorials/inputs/index.html

For example, here is a transcript in Lua of the first code sample from the "Events versus polling" section of the "Input examples" documentation (https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html#events-versus-polling):

```lua
-- NOTE: just like the example in GDScript, this example assumes you
-- have the rest of the script's class defined, like the `jump` method,
-- `position` and `speed` properties
function MyClass:_input(event)
  if event:is_action_pressed("jump") then
    self:jump()
  end
end

function MyClass:_physics_process(delta)
  if Input:is_action_pressed("move_right") then
    self.position.x = self.position.x + self.speed * delta
  end
end
```

**Comment by srichand2095** [comment]
hey
i still have some issues can please send a demo if you don't mind.

**Comment by gilzoide** [comment]
You'll have to be more specific with what you're trying to make.
I could make a demo, but it might not do exactly what you're trying to do, since Godot has more than one way of handling input and each project has their own requirements.

**Comment by srichand2095** [comment]
hi
thanks for helping me out.i am a beginner and i have may doubts. i will
reach out if anything goes wrong.
i am thankful.

**Comment by gilzoide** [comment]
No problem! ^^
