### ISSUE TITLE
Plugin not working in Godot 4.0

### ISSUE THREAD

**Issue by mkukiro** [gilzoide/godot-lua-pluginscript#48]
I can't enable the plugin on Godot 4.0 as it throws this error:
 `Unable to load addon script from path: 'res://addons/godot-lua-pluginscript/plugin/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot-lua-pluginscript/plugin/plugin.cfg' to prevent further errors.`

- Fedora Linux 37
- Godot version 4.0 stable
- Latest luapluginscript release

**Comment by gilzoide** [comment]
Hi @mkukiro.
This plugin relies on GDNative/PluginScript, a Godot 3.X only technology, and does not/will not support Godot 4.

For now, the only "use Lua from Godot" plugin I know that supports Godot 4 is [WeaselGames/godot_luaAPI](WeaselGames/godot_luaAPI). There is also [Fumohouse/godot-luau-script](https://github.com/Fumohouse/godot-luau-script) for using Luau, a variant of Lua, in Godot.

I'm already planning on a port of a Lua PluginScript-like addon for Godot 4, but since it needs a complete rewrite, it will take some time (maybe a lot of time, I'm not sure).

**Comment by gilzoide** [comment]
I've added a WARNING in the README about that, since you are not the first one to come here with an issue about Lua PluginScript not working with Godot 4. I also submitted an edit to the Asset Library adding "(Godot 3.X)" to the asset's name, to make it clear that this does not support Godot 4.
